### ISSUE TITLE
Question on user config

### ISSUE THREAD

**Issue by jacksonludwig** [wiltaylor/dotfiles#1]
Hi, I watched your youtube videos and have been checking out your dotfiles to try to understand better how nix works.

I was wondering how you activate your user configuration, In your tutorials you had a separate script for updating user/home-manager and system-wide configuration. Is that the same here? I only see an `apply` script in the repo.

thanks for your help.

**Comment by wiltaylor** [comment]
Hi @jacksonludwig, yeah I do need to clean my dotfiles up a bit and make them more usable for other people.

I actually have a script called sys that I bundle all of my system maintenance stuff up into.

It is located here:
https://github.com/wiltaylor/dotfiles/blob/master/roles/core/scripts.nix

**Comment by jacksonludwig** [comment]
thanks for the info, would you maybe also be able to clarify what the `shells` section ([here](https://github.com/wiltaylor/dotfiles/blob/46edbaae9935eba8be22075a11a94861c2c2a8b4/flake.nix#L47)) does in your config? 

I see that it uses a helper function to make a nix shell, but I'm not sure how you would run something like that without a shell.nix file.

thanks again!

**Comment by wiltaylor** [comment]
@jacksonludwig Yeah that is something I am going to rework. I am trying to break all of my system config up to be workflow based so i can keep as little in the core as possible. Other things have come up in the last month and a bit though so haven't had a chance to look at it.

As for shells and the confusion of not using a shell.nix file. This is because the way flakes change things. In regular old nix you would run `nix-shell` and it would create a shell from the derivation in shell.nix. Where as with flakes you can do something similar with `nix develop` which will by default create a shell from the derivation found in `devShell.${system}` or you can pass in which output you want it to run as a shell. in my case `nix develop .#shells.video` for example.

I also put a helper function in the sys script i mentioned above to launch these easier.

I am however thinking of breaking these separate shells out into their own flakes (kinda like what i did with my neovim config) so it  is a little easier to follow. I am going to make some more videos on a lot of this too :).

**Comment by jacksonludwig** [comment]
sounds good, thanks for the help
